# fly.toml app configuration file generated for rencom-backend on 2025-07-18T20:07:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'rencom-backend'
primary_region = 'lhr'

[experimental]
  auto_rollback = true

[build]

[env]
  APP_NAME = 'Rencom'
  DEBUG = 'false'
  HOST = '0.0.0.0'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [[http_service.checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
